//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 10:52:57 PM EEST 
//

package org.javamoney.moneta.extras.yhoo.quote;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link YhooRoot }
     * 
     */
    public YhooRoot createList() {
        return new YhooRoot();
    }

    /**
     * Create an instance of {@link YhooRoot.YhooCurrencies }
     * 
     */
    public YhooCurrencies createListResources() {
        return new YhooCurrencies();
    }

    /**
     * Create an instance of {@link YhooRoot.YhooCurrencies.YhooQuoteItem }
     * 
     */
    public YhooQuoteItem createListResourcesResource() {
        return new YhooQuoteItem();
    }

    /**
     * Create an instance of {@link YhooRoot.Meta }
     * 
     */
    public Meta createListMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link YhooRoot.YhooCurrencies.YhooQuoteItem.YhooField }
     * 
     */
    public YhooField createListResourcesResourceField() {
        return new YhooField();
    }

}
